### ISSUE TITLE
NextJs 14 compatibility:`ReferenceError: self is not defined`

### ISSUE THREAD

**Issue by raed667** [slash9494/react-modern-audio-player#20]
When using `react-modern-audio-player` with a Next.js 14 application I get this error even though my component is client rendered.

```
 ✓ Compiled in 134ms (705 modules)
 ⨯ node_modules/react-modern-audio-player/dist/index.es.js (2857:3) @ eval
 ⨯ ReferenceError: self is not defined
    at __webpack_require__ (/Users/code/personal/songlink/.next/server/webpack-runtime.js:33:43)
    at eval (./src/app/track/[key]/preview.tsx:7:83)
    at (ssr)/./src/app/track/[key]/preview.tsx (/Users/code/personal/songlink/.next/server/app/track/[key]/page.js:314:1)
    at __webpack_require__ (/Users/code/personal/songlink/.next/server/webpack-runtime.js:33:43)

```

```tsx
"use client";

import AudioPlayer from "react-modern-audio-player";

const Player = ({ url }) => {
  return (
    <div>
      <AudioPlayer
        playList={[
          {
            id: 1,
            src: url,
          },
        ]}
        audioInitialState={{ volume: 1, curPlayId: 1, repeatType: "ONE" }}
        activeUI={{
          playButton: true,
          progress: "waveform",
        }}
        rootContainerProps={{
          colorScheme: "light",
          scale: "medium",
        }}
      />
    </div>
  );
};
```

**Comment by jhoanborges** [comment]
same +1
![image](https://github.com/user-attachments/assets/ef44f823-4f01-4396-b8dc-5a51aa418e59)

**Comment by JVictoryLiner** [comment]
Here's a WA that I have tried, works for me.

```
"use client";

import dynamic from "next/dynamic";
import { useTheme } from "next-themes";
import { useEffect, useState } from "react";

const AudioPlayer = dynamic(() => import("react-modern-audio-player"), { ssr: false });

export default function CandidateDashboardAudio({ profile }) {
    const { resolvedTheme } = useTheme();
    const [mounted, setMounted] = useState(false);

    useEffect(() => {
        setMounted(true);
    }, []);

    if (!mounted) {
        return null;
    }

    return (
        <AudioPlayer
            playList={[
                {
                    name: "Introduction",
                    src: profile?.audioUrl,
                    id: 1,
                },
            ]}
            activeUI={{
                playButton: true,
                volume: false,
                progress: "bar",
            }}
            placement={{
                player: "static",
                volumeSlider: "top",
            }}
            rootContainerProps={{
                colorScheme: resolvedTheme === "light" ? "light" : "dark",
                width: "275px",
            }}
        />
    );
}
```

**Comment by Bacteria007** [comment]
in reactjs it is working fine
but  
in next js i am getting this error

<img width="659" alt="Image" src="https://github.com/user-attachments/assets/82041655-ca11-43ce-958b-29cf27586e39" />
