### ISSUE TITLE
Player not work at all - React 18

### ISSUE THREAD

**Issue by Abdullah0991** [slash9494/react-modern-audio-player#8]
Hi, I just found your amazing player and I am trying to use it in my `react 18.2` app, but it keeps crashing and does not render the player.

I tried the latest version: `v1.4.0-rc.2`, and also tried to downgrade to `v1.3.0`.

Code:
```
<Stack spacing={2} py={2}>
    {message.isAudio && <AudioPlayer
        playList={[{ src: getAudioFileFullPath(), id: 1 }]}
        audioInitialState={{ isPlaying: true, curPlayId: 1 }}
        activeUI={{ playButton: true, volume: true, volumeSlider: true, trackTime: true, progress: 'waveform' }}
    />}
    ....
</Stack>
```

Error:
```
Uncaught Error: [object Object] is not provided or null
    at useNonNullableContext (index.es.js:1083:11)
    at usePropsStateEffect (index.es.js:8025:31)
    at AudioPlayer (index.es.js:8079:3)
    at renderWithHooks (react-dom.development.js:16305:18)
    at mountIndeterminateComponent (react-dom.development.js:20074:13)
    at beginWork (react-dom.development.js:21587:16)
    at HTMLUnknownElement.callCallback2 (react-dom.development.js:4164:14)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:16)
    at invokeGuardedCallback (react-dom.development.js:4277:31)
    at beginWork$1 (react-dom.development.js:27451:7)
```

Dependencies:
```
"dependencies": {
  "@date-io/dayjs": "^2.16.0",
  "@emotion/react": "^11.10.5",
  "@emotion/styled": "^11.10.5",
  "@mui/icons-material": "^5.11.0",
  "@mui/material": "^5.11.1",
  "@mui/x-date-pickers": "^5.0.12",
  "axios": "^1.2.4",
  "notistack": "^2.0.8",
  "react": "^18.2.0",
  "react-dom": "^18.2.0",
  "react-hook-form": "^7.41.1",
  "react-modern-audio-player": "^1.3.0",
  "react-query": "^3.39.2",
  "react-router-dom": "^6.5.0",
  "stylis": "^4.1.3",
  "stylis-plugin-rtl": "^2.1.1",
  "usehooks-ts": "^2.9.1"
},
"devDependencies": {
  "@types/react": "^18.0.26",
  "@types/react-dom": "^18.0.9",
  "@types/stylis": "^4.0.2",
  "@vitejs/plugin-react": "^3.0.0",
  "dayjs": "^1.11.7",
  "typescript": "^4.9.3",
  "vite": "^4.0.0"
}
```

**Comment by MarShallOwn** [comment]
Same currently facing this issue and still haven't figured out why it is giving me this error

**Comment by MarShallOwn** [comment]
I found the Issue

I think you are importing the AudioPlayer Component as **(Named Import)** and It should be **(Default Export)**

```
// Wrong Import
import { AudioPlayer } from "react-modern-audio-player"; ❌

// Correct Import
import AudioPlayer from "react-modern-audio-player"; ✔
```
